<?php
return [
  'api-version'=>'v1.1',
    'api-version-v2'=>'v2',
    'get-customer'=>'customer/get',
    'add-customer'=>'customer/add',
    'usergroups'=>'usergroups',
    'get-transaction'=>'customer/transactions',
    'coupon-isredeemable'=>'coupon/isredeemable',
    'get-product'=>'product/get',
    'points-isredeemable'=>'points/isredeemable',
    'get-tickets'=>'customer/tickets',
    'changeIdentifier'=>'changeIdentifier',
    'search-customer'=>'customers/lookup/customerDetails',
    'customers'=>'customers',
    'coupons'=>'coupons',
    'get-otp'=>'otp/generate',
    'otp-validate'=>'otp/validate',
    'referral-validate'=>'referral/validate',
    'update-customer'=>'customer/update',
    'add-transaction'=>'transaction/add',
    'reverse-point'=>'points/reverse',
    'redeem-coupon'=>'coupon/redeem',
    'redeem-point'=>'points/redeem',
    'api_gateway-gamification-v1-brand'=>'api_gateway/gamification/v1/brand/',
    'user-all-games'=>'user/games/all',
    'user-game'=>'user/games',
    'api_gateway-rewards-core-v1-user-reward-brand'=>'api_gateway/rewards/core/v1/user/reward/brand',
    'api_gateway-rewards-core-v1-user-vouchers-brand'=>'api_gateway/rewards/core/v1/user/vouchers/brand',

    'shopify-admin'=>'admin/api',
    'shopify-version'=>'2022-10',
    'shopify-customers'=>'customers'

];

/*return [
  'api-version'=>'v1.1',
    'api-version-v2'=>'v2',
    'get-customer'=>'get-customers',
    'add-customer'=>'add-customer',
    'usergroups'=>'usergroups',
    'get-transaction'=>'customer/transactions',
    'coupon-isredeemable'=>'coupon/isredeemable',
    'get-product'=>'product/get',
    'points-isredeemable'=>'are-points-redeemable',
    'get-tickets'=>'customer/tickets',
    'changeIdentifier'=>'changeIdentifier',
    'search-customer'=>'customers/lookup/customerDetails',
    'customers'=>'customers',
    'coupons'=>'coupons',
    'get-otp'=>'otp/generate',
    'otp-validate'=>'otp/validate',
    'referral-validate'=>'referral/validate',
    'update-customer'=>'customer/update',
    'add-transaction'=>'transaction/add',
    'reverse-point'=>'points-reverse',
    'redeem-coupon'=>'coupon/redeem',
    'redeem-point'=>'redeem-points',
    'api_gateway-gamification-v1-brand'=>'api_gateway/gamification/v1/brand/',
    'user-all-games'=>'user/games/all',
    'user-game'=>'user/games',
    'api_gateway-rewards-core-v1-user-reward-brand'=>'api_gateway/rewards/core/v1/user/reward/brand',
    'api_gateway-rewards-core-v1-user-vouchers-brand'=>'api_gateway/rewards/core/v1/user/vouchers/brand',

    'shopify-admin'=>'admin/api',
    'shopify-version'=>'2022-01',
    'shopify-customers'=>'customers'

];*/
